service: change-service
plugins:
  - serverless-domain-manager
custom:
  changeStage: ${opt:stage, self:provider.stage}
  changeEnvironment:
    CIS_ENVIRONMENT:
      production: production
      development: development
      testing: testing
    DYNAMODB_TABLE:
      production: production-identity-vault
      development: development-identity-vault
      testing: testing-identity-vault
    IDENTIFIER:
      production: api.sso.mozilla.com
      development: api.dev.sso.allizom.org
      testing: api.test.sso.allizom.org
    CIS_KINESIS_ARN:
      production: arn:aws:kinesis:us-west-2:320464205386:stream/cis-input-production
      development: arn:aws:kinesis:us-west-2:320464205386:stream/cis-input-development
      testing: arn:aws:kinesis:us-west-2:320464205386:stream/cis-input-testing
    CIS_DYNAMODB_ARN:
      production: arn:aws:dynamodb:us-west-2:320464205386:table/production-identity-vault
      development: arn:aws:dynamodb:us-west-2:320464205386:table/development-identity-vault
      testing: arn:aws:dynamodb:us-west-2:320464205386:table/testing-identity-vault
    CHANGE_SERVICE_AUTH0_DOMAIN:
      production: auth.mozilla.auth0.com
      development: auth.mozilla.auth0.com
      testing: auth.mozilla.auth0.com
    CIS_JWT_VALIDATION:
      production: true
      development: true
      testing: false
    CIS_ENFORCE_PUBLISHER_RULES:
      production: true
      development: true
      testing: false
    CIS_ENFORCE_SIGNATURES:
      production: true
      development: true
      testing: false
    DOMAIN_NAME:
      production: change.api.sso.mozilla.com
      development: change.api.dev.sso.allizom.org
      testing: change.api.test.sso.allizom.org
  customDomain:
    domainName: ${self:custom.changeEnvironment.DOMAIN_NAME.${self:custom.changeStage}}
    basePath: ''
    stage: ${self:custom.changeStage}
    endpointType: edge
    createRoute53Record: true
    certificateName: ${self:custom.changeEnvironment.DOMAIN_NAME.${self:custom.changeStage}}
provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  environment:
    CIS_KINESIS_ARN: ${self:custom.changeEnvironment.CIS_KINESIS_ARN.${self:custom.changeStage}}
    CIS_DYNAMODB_ARN: ${self:custom.changeEnvironment.CIS_DYNAMODB_ARN.${self:custom.changeStage}}
    CIS_ENVIRONMENT: ${self:custom.changeEnvironment.CIS_ENVIRONMENT.${self:custom.changeStage}}
    CIS_STREAM_BYPASS: true
    CIS_ASSUME_ROLE_ARN: None
    CIS_REQUESTS_CACHE_BACKEND: memory
    CIS_DYNAMODB_TRANSACTIONS: true
    CIS_JWT_VALIDATION: ${self:custom.changeEnvironment.CIS_JWT_VALIDATION.${self:custom.changeStage}}
    CIS_VERIFY_PUBLISHERS: ${self:custom.changeEnvironment.CIS_ENFORCE_PUBLISHER_RULES.${self:custom.changeStage}}
    CIS_VERIFY_SIGNATURES: ${self:custom.changeEnvironment.CIS_ENFORCE_SIGNATURES.${self:custom.changeStage}}
    CHANGE_SERVICE_AUTH0_DOMAIN: ${self:custom.changeEnvironment.CHANGE_SERVICE_AUTH0_DOMAIN.${self:custom.changeStage}}
    CIS_ENFORCE_PUBLISHER_RULES: ${self:custom.changeEnvironment.CIS_ENFORCE_PUBLISHER_RULES.${self:custom.changeStage}}
    CHANGE_SERVICE_API_IDENTIFIER: ${self:custom.changeEnvironment.IDENTIFIER.${self:custom.changeStage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "kinesis:DescribeStream"
        - "kinesis:PutRecord"
        - "kinesis:PutRecords"
      Resource:
        - ${self:custom.changeEnvironment.CIS_KINESIS_ARN.${self:custom.changeStage}}
    - Effect: Allow
      Action:
        - "dynamodb:ConditionCheckItem"
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:TransactWriteItems"
        - "dynamodb:UpdateItem"
      Resource:
        - ${self:custom.changeEnvironment.CIS_DYNAMODB_ARN.${self:custom.changeStage}}
functions:
  api:
    handler: handler.handle
    description: serverless-wsgi based endpoint to recieve profile changes.
    memorySize: 512
    timeout: 15
    events:
      - http: ANY /
      - http: ANY {proxy+}
    layers:
      -  ${ssm:/iam/cis/${self:custom.changeStage}/lambda_layer_arn}
