service: profile-retrieval
custom:
  profileRetrievalStage: ${opt:stage, self:provider.stage}
  profileRetrievalEnvironment:
    CIS_ENVIRONMENT:
      production: production
      development: development
      testing: testing
    DYNAMODB_TABLE:
      production: production-identity-vault
      development: development-identity-vault
      testing: testing-identity-vault
    IDENTIFIER:
      production: https://api.sso.mozilla.com
      development: https://api.sso.allizom.org
      testing: https://api.sso.allizom.org
    CIS_DYNAMODB_ARN:
      production: arn:aws:dynamodb:us-west-2:320464205386:table/production-identity-vault
      development: arn:aws:dynamodb:us-west-2:320464205386:table/development-identity-vault
      testing: arn:aws:dynamodb:us-west-2:320464205386:table/testing-identity-vault
    PERSON_API_AUTH0_DOMAIN:
      production: auth.mozilla.auth0.com
      development: auth-dev.mozilla.auth0.com
      testing: auth-dev.mozilla.auth0.com
    CIS_JWT_VALIDATION:
      production: true
      development: true
      testing: false
provider:
  name: aws
  runtime: python3.6
  environment:
    CIS_DYNAMODB_ARN: ${self:custom.profileRetrievalEnvironment.CIS_DYNAMODB_ARN.${self:custom.profileRetrievalStage}}
    CIS_ENVIRONMENT: ${self:custom.profileRetrievalEnvironment.CIS_ENVIRONMENT.${self:custom.profileRetrievalStage}}
    CIS_ASSUME_ROLE_ARN: None
    CIS_REQUESTS_CACHE_BACKEND: memory
    PERSON_API_AUTH0_DOMAIN: ${self:custom.profileRetrievalEnvironment.PERSON_API_AUTH0_DOMAIN.${self:custom.profileRetrievalStage}}
    PERSON_API_API_IDENTIFIER: ${self:custom.profileRetrievalEnvironment.IDENTIFIER.${self:custom.profileRetrievalStage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
      Resource:
        - ${self:custom.profileRetrievalEnvironment.CIS_DYNAMODB_ARN.${self:custom.profileRetrievalStage}}/*
        - ${self:custom.profileRetrievalEnvironment.CIS_DYNAMODB_ARN.${self:custom.profileRetrievalStage}}
functions:
  api:
    handler: handler.handle
    description: serverless-wsgi based endpoint to retrieve profiles aka person-api.
    memorySize: 512
    timeout: 15
    events:
      - http: ANY /
      - http: ANY {proxy+}
    layers:
      - arn:aws:lambda:us-west-2:320464205386:layer:cis_development:73
