language: python
dist: trusty
cache: pip
python:
  - 3.6
before_install:
  - sudo rm -f /etc/boto.cfg
  - pip install flake8
  - pip install tox
  - npm install -g dynalite
  - npm install -g kinesalite
script:
  - export BOTO_CONFIG=/dev/null
  - export AWS_ACCESS_KEY_ID=foo
  - export AWS_SECRET_ACCESS_KEY=bar
  - export DEFAULT_AWS_REGION=us-west-2
  - cd python-modules && make test-tox
