language: python
python:
  - 3.6
env:
  - "AWS_DEFAULT_REGION=us-west-2 AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy BOTO_CONFIG=/dev/null"
before_install:
  - sudo rm -f /etc/boto.cfg
  - pip install flake8
  - pip install tox
script:
  - export BOTO_CONFIG=/dev/null
  - cd python-modules && make test-tox
