AWSTemplateFormatVersion: 2010-09-09
Description: Create the hris s3 buckets.
Parameters:
  StageParameter:
    Type: String
    Default: development
    AllowedValues:
      - production
      - development
      - test
    Description: Enter production, development, or test.
Resources:
  hrisBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: application
          Value: cis
        - Key: environment
          Value: !Ref StageParameter
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Description: Name of the s3 bucket we created.
    Value: !Ref hrisBucket
