service: ldap-publisher
provider:
  name: aws
  runtime: python3.6
  environment:
    CIS_CHANGE_ENDPOINT_DOMAIN: ze4nhrltib.execute-api.us-west-2.amazonaws.com
    CIS_CHANGE_ENDPOINT_ROUTE: /development/change
    CIS_ENVIRONMENT: development
    CIS_S3_BUCKET_NAME: dev-cis-ldap2s3-publisher-data
    CIS_LDAP_JSON_FILE: ldap-full-profile-v2.json.xz
    LDAP_ASSUME_ROLE_ARN: arn:aws:iam::656532927350:role/cisv2-development-ldap-publisher
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sts:AssumeRole"
      Resource:
        - arn:aws:iam::656532927350:role/cisv2-development-ldap-publisher
    - Effect: Allow
      Action:
        - "ssm:GetParameterHistory"
        - "ssm:GetParametersByPath"
        - "ssm:GetParameters"
        - "ssm:GetParameter"
      Resource:
        - arn:aws:ssm:us-west-2:320464205386:parameter/iam/ldap-publisher/development/*
    - Effect: Allow
      Action:
        - "kms:Decrypt"
      Resource:
        - arn:aws:kms:us-west-2:320464205386:key/ef00015d-739b-456d-a92f-482712af4f32
functions:
  publisher:
    handler: handler.handle
    description: Lambda function periodically sending ldap users to the identity vault.
    memorySize: 1024
    timeout: 900
    layers:
      - arn:aws:lambda:us-west-2:320464205386:layer:cis_development:44
    onError: arn:aws:sns:us-west-2:320464205386:cis-dev-dlq
