service: profile-retrieval
provider:
  name: aws
  runtime: python3.6
  environment:
    CIS_KINESIS_ARN: arn:aws:kinesis:us-west-2:320464205386:stream/cis-input-development
    CIS_DYNAMODB_ARN: arn:aws:dynamodb:us-west-2:320464205386:table/development-identity-vault
    CIS_ENVIRONMENT: development
    CIS_ASSUME_ROLE_ARN: None
    CIS_REQUESTS_CACHE_BACKEND: memory
    PERSON_API_AUTH0_DOMAIN: auth-dev.mozilla.auth0.com
    PERSON_API_API_IDENTIFIER: https://api.sso.allizom.org
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
      Resource:
        - arn:aws:dynamodb:us-west-2:320464205386:table/development-identity-vault/*
        - arn:aws:dynamodb:us-west-2:320464205386:table/development-identity-vault
functions:
  api:
    handler: handler.handle
    description: serverless-wsgi based endpoint to retrieve profiles aka person-api.
    memorySize: 512
    timeout: 15
    events:
      - http: ANY /
      - http: ANY {proxy+}
    layers:
      - arn:aws:lambda:us-west-2:320464205386:layer:cis_development:50
